cmdb/cmdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^search/$','main.views.search'),
	url(r'^list/$','main.views.listhost'),
	url(r'^$','main.views.search'),
	url(r'^addhost/','main.views.addhost'),
]

cmdb/main/models.py
from django.db import models

# Create your models here.


class Hostgroup(models.Model):
	groupname = models.CharField(max_length=30)

	def __unicode__(self):
		return self.groupname


class Region(models.Model):
	regionname = models.CharField(max_length=30, default='cn-hangzhou')

	def __unicode__(self):
		return self.regionname


class Search(models.Model):
	times = models.IntegerField()

	def __unicode__(self):
		return str(self.times)

	def add(self):
		self.times += 1
		self.save()


class OsManager(models.Manager):

	def create_os(self, name):
		os = self.create(osname=name)
		return os


class Os(models.Model):
	osname = models.CharField(max_length=10, default='Centos6', blank=True, unique=True)

	def __unicode__(self):
		return self.osname

	objects = OsManager()
	#@classmethod
	#def create(cls,name):
	#	os = cls(osname=name)
	#	return os


class Dbtype(models.Model):
# dbname = models.CharField(max_length=20,unique=True)

	def setval(self,mem,con,iops):
		self.mem = mem
		self.connections = con
		self.iops = iops
	mem = models.IntegerField(unique=True)
	connections = models.IntegerField()
	iops = models.IntegerField()

	def __unicode__(self):
		return "%sMB %i %i" % (self.mem, self.connections, self.iops)


class Rds(models.Model):
	group = models.ForeignKey(Hostgroup)
	dns = models.CharField(max_length=50)
	dbtype = models.ForeignKey(Dbtype)

	def __unicode__(self):
		return "%s %s" % (self.dns,self.dbtype)
#type ,mem,connections,iops

	Region = models.ForeignKey(Region,default=6)
	

class Host(models.Model):
	CRegions = (
		('hz','cn-hangzhou'),
		('ss','cn-shenzhen'),
		('qd','cn-qingdao'),
		('bj','cn-beijing'),
		('sh','cn-shanghai'),
		('hk','cn-hongkong'),
		('us1','us-west-1'),
	)
	group = models.ForeignKey(Hostgroup)
	os = models.ForeignKey(Os, default=1)
	hostname = models.CharField(max_length=30, unique=True)
	eth0 = models.GenericIPAddressField(unique=True)
	eth1 = models.GenericIPAddressField(blank=True, null=True )
	beizhu = models.TextField(blank=True)
#	Region = models.CharField(max_length=3,choices=CRegions)
	Region = models.ForeignKey(Region, default=6)
#	test = models.TextField()
#	test2 = models.TextField()

	def __unicode__(self):
		return '%s %s %s %s' % (self.hostname, self.eth0, self.eth1, self.group)
#	RegionID = 
#	os = 
#	cpu = 
#	memory = 

cmdb/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from .models import Host,Search,Hostgroup,Rds
# Create your views here.

class Searchbox(forms.Form):
	host = forms.CharField(max_length=30)

def search( request ):
#	hosts = Host.objects.all()
	if request.method == 'POST':
		form = Searchbox(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			print cd['host']
			hosts = Host.objects.filter(hostname__contains=cd['host'] )
			s = Search.objects.get()
			s.add()
#			s.times += 1
#			s.save()
			
			#hosts = Host.objects.get(hostname__iexact = cd['host'] )
			print hosts
#			host_list = []
#			for h in hosts:
#				print h.hostname.find(cd['host'])
#				if h.hostname.find(cd['host']) != -1:
#				#if h.hostname == cd['host']:
#					host_list.append(h)
	
#			return HttpResponse('ok')
			return render( request,'search.html',{ 'form':form ,'hosts':hosts,'times':s.times})
			#return render( request,'search.html',{ 'form':form ,'hosts':host_list})
	else:
		form = Searchbox()
	return 	render( request,'search.html',{ 'form':form })
		
def listhost( request ):
	hosts = Host.objects.all()
#	groups =  Hostgroup.objects.all()
	rdss= Rds.objects.all()
	return render( request, 'list.html',{ 'hosts': hosts,'rdss':rdss} )

def addhost( request):
	if request.method == 'GET': 
		h_name = request.REQUEST.get('hostname')
		
	return HttpResponse('ok')

cmdb/main/templates/list.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<html>

<!-- <h1>host lists</h1> -->
<div class="panel panel-default">
	<div class="panel-heading">Rds Lists </div>
<table border="1">
{% for host in hosts %}
	<tr>
		<th>{{ host.hostname }} </th>
		<th>{{ host.eth0 }} </th>
		<th>{{ host.eth1 }} </th>
		<th> {{ host.group }} </th>	
	</tr>
{% endfor %}
</table>
</div>
<!-- <h1>RDS lists</h1> -->

<div class="panel panel-default">
	<div class="panel-heading">Rds Lists </div>
<table border="1">
{% for rds in rdss %}
	<tr>
		<th> {{rds.dns}} </th>
		<th> {{rds.dbtype.mem}}MB </th>
		<th> {{rds.dbtype.connections}} </th>
		<th> {{rds.dbtype.iops}} </th>
		<th> {{rds.group}} </th>
	</tr>

{% endfor %}
</table>
</div>
</html>

cmdb/main/templates/search.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<html>
<h1>search </h1>
  {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

<div class="input-group">
<form action="" method="POST">
	{% csrf_token %}
	<p><label for="id_host">Host:</label> <input id="id_host"   maxlength="30" name="host" type="text" />
<!--	<table>
		{% csrf_token %}
		{{ form.as_ul }}
	</table> -->
	<input type="submit" value="Submit" > 
	</p>
	<!-- <input type="submit" value="Submit" class="form-control"> -->
</form>
</div>

<table border="1">
{% if hosts %}
	<tr> 
		<th>hostname</th>
		<th>eth0</th>
		<th>eth1</th>
		<th>Group</th>
	</tr>
{% endif %}
{% for host in hosts %}
        <tr>
                <th>{{ host.hostname }} </th>
                <th>{{ host.eth0 }} </th>
                <th>{{ host.eth1 }} </th>
                <th> {{ host.group }} </th>
        </tr>
{% endfor %}
</table>
{% if times %}
<li>第{{ times }}次搜索</li>
{% endif %}
</html>